-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create schema if not exists public;

create table public.t_cms_config (
  id                            bigint generated by default as identity not null,
  name                          varchar,
  url                           varchar,
  class_type                    varchar,
  type                          varchar,
  site_id                       varchar,
  description                   varchar,
  status                        varchar,
  progress                      varchar,
  record                        varchar,
  constraint pk_t_cms_config primary key (id)
);

create table scheduled_tasks (
  id                            bigint generated by default as identity not null,
  resource_id                   bigint,
  interval_value                integer,
  enabled                       boolean default false not null,
  last_execution_time           bigint,
  next_execution_time           bigint,
  created_at                    bigint,
  updated_at                    bigint,
  name                          varchar,
  collection_type               varchar,
  interval_unit                 varchar,
  status                        varchar,
  cron_expression               varchar,
  task_class                    varchar,
  execution_result              varchar,
  constraint pk_scheduled_tasks primary key (id)
);

create table public.user (
  id                            bigint generated by default as identity not null,
  name                          varchar,
  phone                         varchar,
  email                         varchar,
  password                      varchar,
  constraint pk_user primary key (id)
);


-- !Downs

-- drop all
drop table if exists public.t_cms_config cascade;

drop table if exists scheduled_tasks cascade;

drop table if exists public.user cascade;

